pipeline {
    agent any

    parameters {
        booleanParam(name: 'BUILD_FRONTEND', defaultValue: true, description: 'Build Next.js Frontend')
        booleanParam(name: 'BUILD_BACKEND', defaultValue: true, description: 'Build Django Backend')
    }

    environment {
        // --- FRONTEND CONFIG ---
        FE_DIR = "frontend"
        FE_IMAGE = "dn7x7-frontend"
        FE_CONTAINER = "dn7x7-frontend-prod"
        FE_PORT = "3100" 

        // --- BACKEND CONFIG ---
        BE_DIR = "backend"
        BE_IMAGE = "dn7x7-backend"
        BE_CONTAINER = "dn7x7-backend-prod"
        BE_PORT = "8100"
        
        // --- PERSISTENT STORAGE (HOST PATHS) ---
        // Media: Uploaded files (Images, etc)
        HOST_MEDIA_PATH = "/var/www/dn7x7/media" 
        // Static: CSS/JS generated by Django (Served by Nginx)
        HOST_STATIC_PATH = "/var/www/dn7x7/static"
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Deploy Frontend') {
            when { expression { return params.BUILD_FRONTEND } }
            steps {
                dir("${FE_DIR}") {
                    withCredentials([file(credentialsId: 'dn7x7-saas-frontend-env', variable: 'FE_ENV_FILE')]) {
                        script {
                            echo "--- Setting up Frontend Environment ---"
                            sh "cp \$FE_ENV_FILE .env.production"

                            echo "--- Building Frontend Image ---"
                            sh "docker build -t ${FE_IMAGE} ."

                            echo "--- Deploying Frontend Container ---"
                            sh "docker stop ${FE_CONTAINER} || true"
                            sh "docker rm ${FE_CONTAINER} || true"

                            sh """
                                docker run -d --restart always \\
                                --name ${FE_CONTAINER} \\
                                -p ${FE_PORT}:3100 \\
                                ${FE_IMAGE}
                            """
                        }
                    }
                }
            }
        }

        stage('Deploy Backend') {
            when { expression { return params.BUILD_BACKEND } }
            steps {
                dir("${BE_DIR}") {
                    withCredentials([file(credentialsId: 'dn7x7-saas-backend-env', variable: 'BE_ENV_FILE')]) {
                        script {
                            echo "--- Preparing Host Directories ---"
                            // 1. Create Host Directories
                            sh "sudo mkdir -p ${HOST_MEDIA_PATH}"
                            sh "sudo mkdir -p ${HOST_STATIC_PATH}"
                            
                            // 2. Set Permissions (UID 1000 matches the 'django' user in Dockerfile)
                            sh "sudo chown -R 1000:1000 ${HOST_MEDIA_PATH} || true"
                            sh "sudo chown -R 1000:1000 ${HOST_STATIC_PATH} || true"
                            
                            echo "--- Preparing Backend Environment ---"
                            sh "cp \$BE_ENV_FILE .env"

                            echo "--- Building Backend Image ---"
                            sh "docker build -t ${BE_IMAGE} ."

                            echo "--- Deploying Backend Container ---"
                            sh "docker stop ${BE_CONTAINER} || true"
                            sh "docker rm ${BE_CONTAINER} || true"

                            // 3. Mount Volumes
                            // -v ${HOST_STATIC_PATH}:/app/staticfiles maps the Host Nginx folder to the Container Django folder
                            sh """
                                docker run -d --restart always \\
                                --name ${BE_CONTAINER} \\
                                --env-file .env \\
                                --add-host=host.docker.internal:host-gateway \\
                                -p ${BE_PORT}:8100 \\
                                -v ${HOST_MEDIA_PATH}:/app/media \\
                                -v ${HOST_STATIC_PATH}:/app/staticfiles \\
                                ${BE_IMAGE}
                            """
                            
                            sh "rm .env"

                            echo "--- Running Migrations & Collecting Static Files ---"
                            sh "docker exec ${BE_CONTAINER} python manage.py migrate"
                            sh "docker exec ${BE_CONTAINER} python manage.py collectstatic --noinput"
                        }
                    }
                }
            }
        }
    }
    
    post {
        always {
            cleanWs()
        }
    }
}